# Generated by Django 4.1.7 on 2023-05-06 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blank_funds', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('link', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='funds',
            new_name='funds_raised',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isOrg',
        ),
        migrations.AddField(
            model_name='organisation',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='organisation',
            name='funds_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blank_funds.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='social',
            field=models.ManyToManyField(blank=True, to='blank_funds.social'),
        ),
    ]
