# Generated by Django 4.2.1 on 2023-05-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank_funds', '0003_social_rename_funds_organisation_funds_raised_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='link',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='name',
            new_name='phone',
        ),
    ]
