# Generated by Django 4.2.1 on 2023-05-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank_funds', '0004_rename_link_social_email_rename_name_social_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='donor_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='donor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
