# Generated by Django 4.2.1 on 2023-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank_funds', '0005_remove_payment_amount_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='social',
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
